version: '3'
services: 
  keycloak:
    image: 'quay.io/keycloak/keycloak:12.0.2'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      # - KEYCLOAK_LOGLEVEL=DEBUG
      # - ROOT_LOGLEVEL=DEBUG
      # - DEBUG=true
    ports: 
      - '8080:8080'
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    volumes: 
      - /app/node_modules
      - ./:/app
    environment: 
      - PORT=3000
      # - AUTH_SERVER_SECURE=false
      # - AUTH_SERVER_HOST=
      # - AUTH_SERVER_PORT=8080
      # - AUTH_SERVER_URI=/auth/
      # - AUTH_SERVER_URL=http://172.26.0.2:8080/auth/
      # - AUTH_SERVER_URL=http://keycloak/auth/
      #using the localhost for keycloak does NOT work - Access denied
      # - AUTH_SERVER_URL=http://localhost:8080/auth/
      #using the external IP for keycloak is working fine
      - AUTH_SERVER_URL=http://172.17.208.1:8080/auth/
      - AUTH_REALM=myrealm
      - AUTH_CLIENT=vanilla
    ports: 
      - '3000:3000'
