apiVersion: v1
kind: Service
metadata:
  name: security-keycloak-app-service
spec:
  type: NodePort
  selector:
    component: security-keycloak-app
  ports:
  - port: 3050
    targetPort: 3000
    nodePort: 30300
